# Generated by Django 4.2 on 2024-02-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='portfolio',
        ),
    ]
